import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { redirect } from "next/navigation";
import Link from "next/link";

export default async function JoinPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  const session = await auth();

  const trip = await prisma.trip.findUnique({
    where: { inviteToken: token },
    select: { id: true, name: true, destination: true },
  });

  if (!trip) {
    return (
      <div className="max-w-sm mx-auto mt-16 px-4 text-center">
        <div className="border border-gray-200 rounded-lg p-6">
          <h1 className="text-xl font-bold text-gray-900 mb-2">Invalid invite link</h1>
          <p className="text-sm text-gray-600">
            This link isn&apos;t valid — it may have been regenerated by the trip owner.
          </p>
        </div>
      </div>
    );
  }

  if (!session?.user?.id) {
    const next = `/join/${token}`;
    return (
      <div className="max-w-sm mx-auto mt-16 px-4 text-center">
        <div className="border border-gray-200 rounded-lg p-6">
          <h1 className="text-xl font-bold text-gray-900 mb-2">You&apos;re invited to {trip.name}</h1>
          <p className="text-sm text-gray-600 mb-4">{trip.destination}</p>
          <p className="text-sm text-gray-600 mb-4">Sign up or log in to join this trip.</p>
          <div className="flex gap-2 justify-center">
            <Link
              href={`/signup?next=${encodeURIComponent(next)}`}
              className="bg-gray-900 text-white text-sm font-medium px-4 py-2 rounded hover:bg-gray-700"
            >
              Sign Up
            </Link>
            <Link
              href={`/login?next=${encodeURIComponent(next)}`}
              className="border border-gray-300 text-gray-700 text-sm font-medium px-4 py-2 rounded hover:bg-gray-50"
            >
              Log In
            </Link>
          </div>
        </div>
      </div>
    );
  }

  const userId = Number(session.user.id);
  const existingMembership = await prisma.tripMember.findUnique({
    where: { tripId_userId: { tripId: trip.id, userId } },
  });

  if (!existingMembership) {
    await prisma.tripMember.create({
      data: { tripId: trip.id, userId, role: "COLLABORATOR" },
    });
  }

  redirect(`/trips/${trip.id}`);
}
